namespace PckTool.Core.WWise.Enums;

public enum PluginId : uint
{
    None = 0x00000000,
    PCM = 0x00010001,
    ADPCM = 0x00020001,
    XMA = 0x00030001,
    VORBIS = 0x00040001,
    WIIADPCM = 0x00050001,
    PCMEX = 0x00070001,           // "Standard PCM WAV file parser for Wwise Authoring"
    EXTERNAL_SOURCE = 0x00080001, // "unknown encoding" (.wem can be anything defined at runtime)
    XWMA = 0x00090001,
    AAC = 0x000A0001,
    FILE_PACKAGE = 0x000B0001, // "File package files generated by the File Packager utility."
    ATRAC9 = 0x000C0001,
    VAG_HE_VAG = 0x000D0001,
    PROFILERCAPTURE = 0x000E0001, // "Profiler capture file (.prof)"
    ANALYSISFILE = 0x000F0001,
    MIDI = 0x00100001,   // .wmid (modified .mid)
    OPUSNX = 0x00110001, // originally just OPUS
    CAF = 0x00120001,    // unused?
    OPUS = 0x00130001,
    OPUS_WEM = 0x00140001,
    OPUS_WEM_2 = 0x00150001, //"Memory stats file as written through AK::MemoryMgr::DumpToFile()"
    SONY360 = 0x00160001,    // unused/internal? '360 Reality Audio', MPEG-H derived?

    // other types
    Wwise_Sine = 0x00640002,               // AkSineTone
    Wwise_Silence = 0x00650002,            // AkSilenceGenerator
    Wwise_Tone_Generator = 0x00660002,     // AkToneGen
    Wwise_Parametric_EQ = 0x00690003,      // AkParametricEQ
    Wwise_Delay = 0x006A0003,              // AkDelay
    Wwise_Compressor = 0x006C0003,         // AkCompressor
    Wwise_Expander = 0x006D0003,           //
    Wwise_Peak_Limiter = 0x006E0003,       // AkPeakLimiter
    Wwise_Matrix_Reverb = 0x00730003,      // AkMatrixReverb
    SoundSeed_Impact = 0x00740003,         //
    Wwise_RoomVerb = 0x00760003,           // AkRoomVerb
    SoundSeed_Air_Wind = 0x00770002,       // AkSoundSeedAir
    SoundSeed_Air_Woosh = 0x00780002,      // AkSoundSeedAir
    Wwise_Flanger = 0x007D0003,            // AkFlanger
    Wwise_Guitar_Distortion = 0x007E0003,  // AkGuitarDistortion
    Wwise_Convolution_Reverb = 0x007F0003, // AkConvolutionReverb
    Wwise_Meter = 0x00810003,              // AkSoundEngineDLL
    Wwise_Time_Stretch = 0x00820003,       // AkTimeStretch
    Wwise_Tremolo = 0x00830003,            // AkTremolo
    Wwise_Stereo_Delay = 0x00870003,       // AkStereoDelay
    Wwise_Pitch_Shifter = 0x00880003,      // AkPitchShifter
    Wwise_Harmonizer = 0x008A0003,         // AkHarmonizer
    Wwise_Gain = 0x008B0003,               // AkGain
    Wwise_Synth_One = 0x00940002,          // AkSynthOne
    Wwise_Reflect = 0x00AB0003,            // AkReflect

    System = 0x00AE0007,                       // DefaultSink
    Communication = 0x00B00007,                // DefaultSink
    Controller_Headphones = 0x00B10007,        // DefaultSink
    Controller_Speaker = 0x00B30007,           // DefaultSink
    No_Output = 0x00B50007,                    // DefaultSink
    Wwise_System_Output_Settings = 0x03840009, // DefaultSink
    SoundSeed_Grain = 0x00B70002,              //
    Mastering_Suite = 0x00BA0003,              // MasteringSuite
    Wwise_3D_Audio_Bed_Mixer = 0x00BE0003,     // Ak3DAudioBedMixer
    Wwise_Audio_Input = 0x00C80002,            // AkAudioInput
    Wwise_Motion_Generator = 0x01950002,       // AkMotion (used in CAkSound, v128>= / v130<=?)
    Wwise_Motion_Generator_2 = 0x01950005,     // AkMotion (used in CAkFeedbackNode, v125<=)
    Wwise_Motion_Source = 0x01990002,          // AkMotion (used in CAkSound, v132>=)
    Wwise_Motion_Source_2 = 0x01990005,        // AkMotion
    Wwise_Motion_ = 0x01FB0007                 // AkMotion
}
